herbs guideline
herbsjs/herbsjs.github.io pull request #161
Opened 2023-03-22 14:34 UTC by tadvortx

Fixes #

# Proposed Changes

1. Include Herbs GuideLine for development

![image](https://user-images.githubusercontent.com/112962515/226937397-7f4ea2f3-70d7-4419-aa79-51984ca90e1c.png)

2023-03-23 22:14 UTC, dalssoft requested changes

2023-03-23 22:14 UTC, dalssoft commented on docs/project/development-guidelines.md
> +**Working with PostgreSQL**
This organization (Working with PostgreSQL / Don't: / Correct) is awkward. I would suggest just Good/Bad or Do/Don't.

2023-03-23 22:14 UTC, dalssoft commented on docs/project/development-guidelines.md
> +By creating the variable this.conn and receiving the connection, we have already passed it to the mother class's knex.
It is not clear in the description why this is not correct.
Also it is not clear what is this "mother class" concept.

2023-03-23 22:14 UTC, dalssoft commented on docs/project/development-guidelines.md
> +To carry out the treatment of errors that occurred during the execution of the usecase, enable the environment variable HERBS_EXCEPTION in the production environments so that Herbs can obfuscate the
link to the doc page for HERBS_EXCEPTION

2023-03-23 22:14 UTC, dalssoft commented on docs/project/development-guidelines.md
> +## Creating custom errors
These are not Custom Errors, but Known errors: https://herbsjs.org/docs/usecase/result#known-errors
Suggestion: "Use Known Errors"

2023-03-23 22:14 UTC, dalssoft commented on docs/project/development-guidelines.md
> +Use Herbs errors to generate metadata for the controller and thus customize your API return.
Suggestion:
User Known Errors to expose runtime metadata. With this runtime information the glues like Herbs2REST or Herbs2GraphQL are able to change the API return.

2023-04-13 11:08 UTC, RodolfoSilva reviewed
LGTM!

2023-04-13 12:04 UTC, dalssoft approved these changes

2023-04-15 00:21 UTC, closed without merging