adding documentation feature
herbsjs/herbsjs.github.io pull request #69
Opened 2021-10-05 22:52 UTC by endersoncosta

adding `usecase.doc()` feature to the usecase documentation

2022-04-14 10:04 UTC, italojs requested changes

2022-04-14 10:04 UTC, italojs commented on .vscode/settings.json
> +        "activityBar.background": "#173415",
we cant upload vscode customizatins, put it into .gitignore, please

2022-04-14 10:05 UTC, italojs commented
you PR has old commits from MAAAANNYYY people, update your branch with the herbs upstream master, please

2022-07-27 19:11 UTC, jhomarolo commented
This pr is under conflict

2022-11-14 12:56 UTC, italojs commented
this PR still alive? could we close it?

2022-11-15 18:54 UTC, dalssoft commented
given the PR poor quality and how old it is, I'm closing this PR.

2022-11-15 18:54 UTC, closed without merging