documentation
herbsjs/herbsjs.github.io pull request #83
Opened 2021-12-06 12:56 UTC by danielsous

Fixes #

## Proposed Changes

1. ... Improved how to contribute section

## Readiness Checklist

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request
- [ ] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2021-12-06 19:15 UTC, italojs requested changes

2021-12-06 19:15 UTC, italojs commented on docs/project/contributing.md
> +## Open Development
instead `Open Development`, we could to use `getting started`

2021-12-06 19:15 UTC, italojs commented on docs/project/contributing.md
>  By default **Herbs organization** uses [Angular Commit Message Conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format).
It must to be explained in commit session

2021-12-06 19:15 UTC, italojs commented on docs/project/contributing.md
>  Tools such as [commitizen](https://github.com/commitizen/cz-cli) or [commitlint](https://github.com/conventional-changelog/commitlint) can be used to help contributors and enforce valid commit messag
It must to be explained in commit session

2021-12-06 19:15 UTC, italojs commented on docs/project/contributing.md
>  - Push to your fork and submit a pull request
I think we could to slit it into sessions
## how to "find" a issue
- explain what is a issue
- where is the issues
- < gif >
### how to open a issue
- < gif > 

## "downloading" and running the code
- how to fork, why fork...
- create branch
- run tests
< gif >

## commting and poushing
- how to use commitizen
- < gif >

# PR
- what is a PR
- how to open a great PR
- < gif >


##

2021-12-06 19:15 UTC, italojs commented on docs/project/contributing.md
> +After that, you need to identify that your pain can be a bug, an implementation or just a question, so it is necessary to always check the issues that are open for the project you are using and want
I think this explanation about PR is confuse

2021-12-06 19:15 UTC, italojs commented on docs/project/contributing.md
> +## Community Contributions
I think we could to change to "no-code contributions"

2021-12-06 19:15 UTC, italojs commented on docs/project/contributing.md
> +- Build your confidence as a developer:
instead use topics, we could use titles

2021-12-14 20:52 UTC, italojs requested changes

2021-12-15 21:27 UTC, danielsous commented on docs/project/contributing.md
> +git cz
Done

2021-12-15 21:27 UTC, danielsous commented on docs/project/contributing.md
> +3. Some download forms like .zip will be displayed, but in our case we will use HTTPS.
Done

2021-12-27 13:34 UTC, italojsv commented
could you include this labels?
https://github.com/herbsjs/herbs/labels

2021-12-27 16:10 UTC, jhomarolo commented
Also, please include those links:

Open issues ready to work and without an owner yet: https://github.com/search?o=desc&q=org%3Aherbsjs+label%3Aready-to-work+-label%3Awip+state%3Aopen&s=created&type=Issues

Open issues with work in progress: https://github.com/search?q=org%3Aherbsjs+-label%3Aready-to-work+label%3Awip+state%3Aopen&type=Issues 

Open issued with help wanted or extra attention needed: https://github.com/search?o=desc&q=org%3Aherbsjs+label%3A%22help+wanted%22+state%3Aopen&s=created&type=Issues

2021-12-27 19:40 UTC, italojsv approved these changes

2021-12-27 19:41 UTC, italojs approved these changes

2021-12-27 19:48 UTC, merged

2021-12-27 19:57 UTC, jhomarolo commented on docs/project/contributing.md
> +**Labels** are automatically defined when the issue/PR is opened and are updated if needed by core members.
@danielsous labels are not automatically defined, just the type of issue label is automatically fixed 

Always an org member tag those issues

2021-12-27 19:58 UTC, jhomarolo commented on docs/project/contributing.md
>  We will use the [buchu](https://github.com/herbsjs/buchu) project as an example.
please use herbs as example

2021-12-27 19:58 UTC, jhomarolo commented on docs/project/contributing.md
>  We will use the [buchu](https://github.com/herbsjs/buchu) project as an example.
https://github.com/herbsjs/herbs/

2021-12-27 19:59 UTC, jhomarolo requested changes

2021-12-27 19:59 UTC, jhomarolo commented on docs/project/contributing.md
> +
Please add a Header before this paragraph, like: "Want to know how to start?" or something simular